services:
  web:
    command: >
      sh -c "/app/.venv/bin/python manage.py migrate &&
             /app/.venv/bin/python manage.py runserver 0.0.0.0:8000"
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
    volumes:
      - ./config:/app/config
      - ./apps:/app/apps
      - ./manage.py:/app/manage.py
