# Generated by Django 6.1 on 2026-08-15 10:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=255, verbose_name='diagnóstico / motivo')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('total_sessions', models.PositiveIntegerField(default=1, verbose_name='cantidad de sesiones')),
                ('frequency', models.CharField(blank=True, help_text='Ej: 2 veces por semana', max_length=100, verbose_name='frecuencia')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fecha de fin')),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='activo', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='patients.patient', verbose_name='paciente')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='número de sesión')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='estado')),
                ('clinical_notes', models.TextField(blank=True, verbose_name='notas clínicas')),
                ('evolution', models.TextField(blank=True, verbose_name='evolución')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='treatments.treatment', verbose_name='tratamiento')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
