# Generated by Django 6.1 on 2026-08-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('treatment', 'number'), name='unique_session_per_treatment'),
        ),
    ]
