# Generated by Django 6.1 on 2026-08-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='apellido')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='domicilio')),
                ('health_insurance', models.CharField(blank=True, max_length=120, verbose_name='obra social')),
                ('reason', models.TextField(blank=True, verbose_name='motivo de consulta')),
                ('notes', models.TextField(blank=True, verbose_name='notas / historia')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
