# Generated by Django 6.1 on 2026-08-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='health_insurance',
        ),
    ]
