# Generated by Django 6.1 on 2026-08-15 13:23

from django.db import migrations
from django.db.models.functions import Upper


def uppercase_dnis(apps, schema_editor):
    Patient = apps.get_model("patients", "Patient")
    Patient.objects.update(dni=Upper("dni"))


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_remove_patient_health_insurance"),
    ]

    operations = [
        migrations.RunPython(uppercase_dnis, migrations.RunPython.noop),
    ]
