# Generated by Django 6.1 on 2026-08-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_uppercase_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dni',
            field=models.CharField(help_text='Ej.: 12345678A', max_length=20, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, help_text='Ej.: nombre@correo.com', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, help_text='Ej.: 612 345 678', max_length=30, verbose_name='teléfono'),
        ),
    ]
