# Generated by Django 6.1 on 2026-08-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_dni_alter_patient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='fatigue_level',
            field=models.CharField(blank=True, choices=[('muy_alto', 'Muy alto'), ('alto', 'Alto'), ('normal', 'Normal'), ('bajo', 'Bajo'), ('muy_bajo', 'Muy bajo')], max_length=20, verbose_name='nivel de cansancio'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gluten_intolerance',
            field=models.BooleanField(blank=True, null=True, verbose_name='intolerancia a gluten'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gut_issues',
            field=models.BooleanField(blank=True, null=True, verbose_name='problemas intestinales'),
        ),
        migrations.AddField(
            model_name='patient',
            name='history',
            field=models.TextField(blank=True, verbose_name='antecedentes'),
        ),
        migrations.AddField(
            model_name='patient',
            name='job',
            field=models.CharField(blank=True, max_length=150, verbose_name='trabajo'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medications',
            field=models.TextField(blank=True, verbose_name='uso de medicamentos'),
        ),
        migrations.AddField(
            model_name='patient',
            name='sport_habits',
            field=models.BooleanField(blank=True, null=True, verbose_name='hábitos deportivos'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='apellidos'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='notes',
            field=models.TextField(blank=True, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reason',
            field=models.TextField(blank=True, verbose_name='motivo de la consulta'),
        ),
    ]
