# Generated by Django 6.1 on 2026-08-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='start',
            field=models.DateTimeField(db_index=True, verbose_name='fecha y hora'),
        ),
    ]
