# Generated by Django 6.1 on 2026-08-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='session',
        ),
    ]
