# Generated by Django 6.1 on 2026-08-15 12:05

from django.db import migrations, models


def dedupe_appointment_starts(apps, schema_editor):
    """Conserva una cita por horario; el resto se marcan como canceladas.

    Necesario antes de aplicar la constraint de unicidad en `start`, que
    fallaría si existen duplicados (p. ej. datos creados sin pasar por la
    validación de la API o del panel). Las canceladas quedan fuera de la
    constraint condicional y no bloquean re-reservas.
    """
    Appointment = apps.get_model("appointments", "Appointment")
    seen = set()
    for appointment in Appointment.objects.order_by("created_at", "pk"):
        if appointment.start in seen:
            appointment.status = "cancelada"
            appointment.save(update_fields=["status"])
        else:
            seen.add(appointment.start)


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_remove_appointment_session"),
        ("patients", "0002_remove_patient_health_insurance"),
    ]

    operations = [
        migrations.RunPython(dedupe_appointment_starts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                fields=("start",),
                condition=models.Q(
                    status__in=("programada", "confirmada", "completada")
                ),
                name="unique_appointment_start",
            ),
        ),
    ]
