# Generated by Django 6.1 on 2026-08-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_unique_appointment_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.PositiveIntegerField(default=50, verbose_name='duración (minutos)'),
        ),
    ]
